name: pyvista-environment
channels:
  - pyviz
dependencies:
  - python=3.7
  - bokeh
  - pyviz_comms
  - panel
  - lxml
  - pip:
    - git+git://github.com/pyvista/pyvista@master
    - scipy
    - matplotlib
    - pyct
